sudo: required

services:
    - docker

script:
    - docker build -t jawsie/node .
    - docker images jawsie/node

before_deploy:
    - docker login -u jawsie -p Jaw12345678

deploy:
    provider: script
    script: docker push jawsie/node
    on:
        branch: master

